version: '3.1'

services:
  redis:
    image: redis:7
    networks:
      - hmpps_int
    ports:
      - "6379:6379"

  wiremock-test:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    ports:
      - "9091:8080"

networks:
  hmpps_int:
