version: '3.1'

services:
  redis:
    image: redis:7
    networks:
      - hmpps
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  wiremock:
    image: wiremock/wiremock
    command:
      - --local-response-templating
    networks:
      - hmpps
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock

  app:
    build: .
    networks:
      - hmpps
    depends_on: [redis]
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - API_CLIENT_ID=sentence-plan-client
      - API_CLIENT_SECRET=sentence-plan-client
      - SYSTEM_CLIENT_ID=sentence-plan-api-client
      - SYSTEM_CLIENT_SECRET=sentence-plan-api-client

networks:
  hmpps:
